spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aieducation
    username: postgres
    password: root
  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo
        base-url: https://api.openai.com/v1/chat/completions
        api-key: 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
      api-key: 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
      base-url: https://api.openai.com/v1/chat/completions
#
#openai:
#  model: gpt-3.5-turbo
#
#openai.model=gpt-3.5-turbo
#openai.api.url=https://api.openai.com/v1/chat/completions
#openai.api.key=your-api-key